import type { NextPage } from "next";
import Head from "next/head";
import DonatePage from "../components/donatePage/home";

const Donate: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Davin Software Foundation</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <DonatePage />
    </div>
  );
};

export default Donate;
